### ISSUE TITLE
Option to Report A Tweet

### ISSUE THREAD

**Issue by theanthonydavenport** [dimdenGD/OldTwitter#716] opened 2024-03-26 18:16 UTC
This is something we'd all hope to be implemented, as it's an essential feature.
<img width="228" alt="Screenshot 2024-03-26 at 18 16 13" src="https://github.com/dimdenGD/OldTwitter/assets/99144439/87d84096-0151-48ef-832d-823578cd4b75">

**Comment by dimdenGD** [comment] 2024-03-26 18:18
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/576
This won't be implemented because it's a critical API and isn't possible to properly test

**Closed by dimdenGD** 2024-03-26 18:18 UTC
Labels: enhancement
