### ISSUE TITLE
Some videos are loading in corrupted

### ISSUE THREAD

**Issue by Zaneclodon** [dimdenGD/OldTwitter#498] opened 2023-09-06 02:46 UTC
**Describe the bug**
Some videos are loading in what appears to be a corrupted state, consisting of a black screen with either silence or seemingly random odd noises. The thumbnail appears as normal before the video is clicked. If the video is downloaded, it won't play in a video player. Changing the quality has no effect.

**Screenshots**
![A tweet with a black screen in place of a video.](https://github.com/dimdenGD/OldTwitter/assets/28819708/3567b86a-9688-418e-972c-fd8b8985ded2)

**Browser**
Firefox 117.0 (64-bit)

**Links**
Tweet in screenshot: https://twitter.com/NintendoAmerica/status/1699226711290782089
Direct video link: https://video.twimg.com/amplify_video/1699226434428977152/vid/avc1/640x360/VbXUwgkW-O7yJwrI.mp4

**OldTwitter version**
v1.7.8.2

**Comment by dimdenGD** [comment] 2023-09-06 09:02
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/32

**Closed by dimdenGD** 2023-09-06 09:02 UTC
Labels: bug
