### ISSUE TITLE
Timeline Won't Load

### ISSUE THREAD

**Issue by AtomicMousetrap** [dimdenGD/OldTwitter#607] opened 2023-11-20 10:34 UTC
**Describe the bug**
Personal timeline loads nothing, but other features work perfectly, such as loading someone else's page.

**Screenshots**
see attached
![image_2023-11-20_053308669](https://github.com/dimdenGD/OldTwitter/assets/151521836/b8601459-fda1-4fc7-a233-9057da76e107)

**Browser**
Opera One(version: 104.0.4944.54)

**Links**
personal timeline

**OldTwitter version**
v1.8.1.4

**Comment by themattreinhart** [comment] 2023-11-21 00:25
Did you try a hard refresh? Sometimes I also had this on Firefox, but with Shift+F5, it refreshes and it will show the timeline.

Not a bug, but occassionally due to a cache issue with fetching new tweets.

**Comment by dimdenGD** [comment] 2023-11-21 14:50
Can't reproduce

**Comment by PixelHir** [comment] 2023-11-21 20:44
Also happens to me occasionally, cant find a reliable method to reproduce

**Comment by jonm58** [comment] 2023-11-21 23:35
hi guys,i need help
![图片](https://github.com/dimdenGD/OldTwitter/assets/73036321/f2a6a50a-85ab-4e92-bd3e-1a2de181e2c4)

**Comment by ayaaop** [comment] 2023-11-22 03:24
![Screenshot_20231122-092341_Pixel_Launcher](https://github.com/dimdenGD/OldTwitter/assets/58212796/7f1bb614-d130-4ec8-ac91-50ba65d2fb55)

**Comment by SageSystems** [comment] 2023-11-22 04:48
same issue, after logging into new twitter instead it says it's a rate limit.

**Comment by SageSystems** [comment] 2023-11-22 04:48
this is a rate limit issue

**Comment by SageSystems** [comment] 2023-11-22 04:51
algorithmic timeline works. however

**Comment by themattreinhart** [comment] 2023-11-22 04:53
> algorithmic timeline works. however

Seems like this is only affecting the “Most recent”/chronological ones per what SageSystems, did X/Twitter change again the code?

**Comment by PixelHir** [comment] 2023-11-22 16:25
<img width="1423" alt="image" src="https://github.com/dimdenGD/OldTwitter/assets/7670940/c6f3979b-dff7-4892-8952-af3228fcce3c">
just happened to me again
<img width="907" alt="image" src="https://github.com/dimdenGD/OldTwitter/assets/7670940/af4c8620-5bf2-4441-822c-01db51472f25">


and it happens on algorithmical for you

**Comment by AtomicMousetrap** [comment] 2023-11-22 20:05
Happened again. Some facts:

Here's the error message from the console. 
![image_2023-11-22_150421936](https://github.com/dimdenGD/OldTwitter/assets/151521836/c2ecf698-844b-48a3-a94d-eb1c5c7caccf)

I don't think this is a rate limit thing: loading the timeline in new twitter works fine, as does loading someone's twitter page in oldtwitter. 

hard refresh(shift+F5) and deleting cookies didn't help.

**Comment by Saberleo456** [comment] 2023-11-22 23:44
Same errors in console as above, scrolling down multiple pages eventually refuses to load any pages further.

**Comment by dimdenGD** [comment] 2023-11-23 02:09
I pushed a possible fix, you can install latest version manually and check if this fixes it for you

**Comment by Saberleo456** [comment] 2023-11-23 03:50
> I pushed a possible fix, you can install latest version manually and check if this fixes it for you

My issue is fixed with this update, you can scroll over 12 hours and 2000 tweets behind, thank you for the quick fix I hope it's pushed to the Chrome store version soon!

**Closed** 2023-11-27 21:05 UTC
Labels: bug
