### ISSUE TITLE
Refresh Loop

### ISSUE THREAD

**Issue by SomeHuman69** [dimdenGD/OldTwitter#723] opened 2024-04-01 00:11 UTC
Extension causes Twitter to endlessly refresh on Firefox

https://github.com/dimdenGD/OldTwitter/assets/44318492/d39efc87-e0b8-4ea1-bcfd-9629a782f7fb

![1](https://github.com/dimdenGD/OldTwitter/assets/44318492/480f225f-f66b-423c-be87-d185885021e1)
![2](https://github.com/dimdenGD/OldTwitter/assets/44318492/143620be-2345-4f1d-99b8-7e9be6399b75)

OldTwitter 1.8.3.1

**Comment by levblob** [comment] 2024-04-01 01:47
Having the same issue. Same add-on version. Got locked out of my account because of the refreshes and had to disable the add-on. Currently unusable for me :P

**Comment by ak47suk1** [comment] 2024-04-01 02:16
I got same issue on Firefox Nightly on Android and on Windows.

**Comment by SpiritAxolotl** [comment] 2024-04-01 02:59
same issue. firefox latest

**Comment by GJJellyfish** [comment] 2024-04-01 10:13
Same issue, Librewolf 123.0-1 on Windows.

**Comment by dimdenGD** [comment] 2024-04-01 11:14
Can't reproduce on Firefox 124.0.1 on Windows

**Comment by RinGotou** [comment] 2024-04-01 11:39
Firefox 124.0.1 (64-bit) on Mac with latest plugin version has the same issue.

**Comment by RinGotou** [comment] 2024-04-01 11:48
> Firefox 124.0.1 (64-bit) on Mac with latest plugin version has the same issue.

I rollback the plugin version to 1.8.2.4, and page can be loaded again.

**Comment by dimdenGD** [comment] 2024-04-01 12:01
There's a new update (1.8.3.4) available on Firefox Addons store now. Check if it fixes this for you

**Comment by ak47suk1** [comment] 2024-04-01 12:26
```
textInput event has been remapped to beforeinput for compatibility reasons. See https://bugzilla.mozilla.org/show_bug.cgi?id=1739489 for details. bug1739489-draftjs-beforeinput.js:13:9
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/vendor.1decd5ea.js. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/i18n/en.d31f9a9a.js. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/main.514cf9ba.js. (Reason: CORS request did not succeed). Status code: (null).
Cookie “lang” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite home
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/feature-switch-manifest.a0016c6a.js. (Reason: CORS request did not succeed). Status code: (null).
<script> source URI is not allowed in this document: “https://abs.twimg.com/responsive-web/client-web/feature-switch-manifest.a0016c6a.js”. home:336:424
The resource at “https://abs.twimg.com/responsive-web/client-web/vendor.1decd5ea.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. home
The resource at “https://abs.twimg.com/responsive-web/client-web/i18n/en.d31f9a9a.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. home
The resource at “https://abs.twimg.com/responsive-web/client-web/main.514cf9ba.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. home

```

firefox 124.0.1 windows 64-bit

**Comment by RinGotou** [comment] 2024-04-01 12:48
> There's a new update (1.8.3.4) available on Firefox Addons store now. Check if it fixes this for you

seems there's still issue...
in my enviroment it stops infinite refreshing, but the page keeps completely blank and console gives same error/warning.

```
textInput event has been remapped to beforeinput for compatibility reasons. See https://bugzilla.mozilla.org/show_bug.cgi?id=1739489 for details. bug1739489-draftjs-beforeinput.js:13:9
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/vendor.1decd5ea.js. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/i18n/zh.2bbb33ca.js. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/main.514cf9ba.js. (Reason: CORS request did not succeed). Status code: (null).
Cookie “lang” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite home
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://abs.twimg.com/responsive-web/client-web/feature-switch-manifest.a0016c6a.js. (Reason: CORS request did not succeed). Status code: (null).
<script> source URI is not allowed in this document: “https://abs.twimg.com/responsive-web/client-web/feature-switch-manifest.a0016c6a.js”. home:336:424
The resource at “https://abs.twimg.com/responsive-web/client-web/vendor.1decd5ea.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. home
The resource at “https://abs.twimg.com/responsive-web/client-web/i18n/zh.2bbb33ca.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. home
The resource at “https://abs.twimg.com/responsive-web/client-web/main.514cf9ba.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. home

```

**Comment by dimdenGD** [comment] 2024-04-01 13:42
1.8.3.5 is now up on addon store, should be fixed now, check

**Comment by ak47suk1** [comment] 2024-04-01 13:47
![Screenshot_2024-04-01-21-45-29-57_984e1414ae90666a90f12ff17ec14a7f](https://github.com/dimdenGD/OldTwitter/assets/1378534/9ae97d83-71eb-49a5-922b-c0d17b4179b1)

it's working as usual on android firefox nightly.

**Comment by RinGotou** [comment] 2024-04-01 13:49
It works now, thanks for the fix!

**Closed** 2024-04-01 13:50 UTC
Labels: bug
