### ISSUE TITLE
Reload loop and blank page on Firefox 124

### ISSUE THREAD

**Issue by owicalagu** [dimdenGD/OldTwitter#729] opened 2024-04-02 08:26 UTC
**Describe the bug**
Instead of loading Twitter, it reloads the page constantly.

**Screenshots**
Just a blank page.

**Browser**
Firefox 124.0.1

**Links**
twitter.com, x.com, all pages

**OldTwitter version**
1.8.3.3

**Comment by dimdenGD** [comment] 2024-04-02 09:15
Duplicate of #723 update extension

**Closed by dimdenGD** 2024-04-02 09:15 UTC
Labels: bug
