### ISSUE TITLE
Please interface with Blue Blocker.

### ISSUE THREAD

**Issue by sekoku** [dimdenGD/OldTwitter#122] opened 2023-07-03 19:58 UTC
Given El\*n is attempting to monetize Twitter Blue, I'd like the ability to have the auto-block function (and ability to hide Blue Checkmarks that are blocked) of BlueBlocker and other extensions that do Blue Checkmark Blocking/#BlockTheBlue implemented to where I do not give views or see their dog\*bleep\* takes in replies.

Extension: https://chrome.google.com/webstore/detail/blue-blocker/jgpjphkbfjhlbajmmcoknjjppoamhpmm

Functionality wise, it should be "simple" (of course nothing in programming ever is, right? :) ) to implement since there is a "#status-is-blue-verified" or whatever function that Twitter's API uses. Then the matter is working with Blue Blocker and other auto-block functions to run via your own extension/old Twitter layout to do the work for extension users.

Awesome extension otherwise. Would use it since El\*n is in the process is killing old Tweet deck as a main-view for Twitter.

**Comment by dimdenGD** [comment] 2023-07-08 23:31
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/88

**Closed by dimdenGD** 2023-07-08 23:31 UTC
Labels: enhancement
