### ISSUE TITLE
Autoplay videos, but muted (easy change)

### ISSUE THREAD

**Issue by dude22072** [dimdenGD/OldTwitter#401] opened 2023-08-07 08:17 UTC
Add a setting to reflect the way of modern twitter where videos are muted unless you click on them.
Since afaik you're embedding videos using the HTML `<video>` tag you should be able to just do `<video muted>` to achieve this.

**Comment by dimdenGD** [comment] 2023-08-07 21:24
Duplicate of #97

**Closed by dimdenGD** 2023-08-07 21:24 UTC
Labels: enhancement
