### ISSUE TITLE
I dont know what this bug exactly did?

### ISSUE THREAD

**Issue by hoagieenjoyer** [dimdenGD/OldTwitter#39] opened 2023-01-13 17:51 UTC
TypeError: Cannot read properties of undefined (reading ’split’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1119:435) at async renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/home/script.js:259:13) at 1613933730648784896 (OldTwitter v1.6.6.0)

**Comment by dimdenGD** [comment] 2023-01-13 17:52
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/37

**Closed by dimdenGD** 2023-01-13 17:52 UTC
Labels: bug
