### ISSUE TITLE
Full move to x.com (🤢)

### ISSUE THREAD

**Issue by SpiritAxolotl** [dimdenGD/OldTwitter#769] opened 2024-05-17 05:06 UTC
twitter.com links are now x.com links and the site is now in a permanent loop in the migration redirect (https://twitter.com/x/migrate?tok=<token>) with the extension.

goodbye twitter.com o7

**Comment by rachasakr** [comment] 2024-05-17 05:10
+1  currently ping-pong between `https://twitter.com/x/migrate?tok=<token>` and `https://twitter.com/?mx=1`

**Comment by TheAGames10** [comment] 2024-05-17 05:11
Yep. I am unable to use the Firefox addon now. I am no longer a Twitter user at this point. :(

**Comment by Volodesi** [comment] 2024-05-17 05:33
Yeah, had to update my bookmark to get out of the endless loop.

RIP Twitter.com

**Comment by symant233** [comment] 2024-05-17 05:37
Goodbye Twitter.

**Comment by meatgrind89** [comment] 2024-05-17 05:49
Some workaround(?): disable the add-on, open Twitter, site will redirect you to X with no loop, redirect successful, re-enable add-on, add-on works again.

Still, rip Twitter.com

**Comment by VaelophisNyx** [comment] 2024-05-17 06:29
> Some workaround(?): disable the add-on, open Twitter, site will redirect you to X with no loop, redirect successful, re-enable add-on, add-on works again.
> 
> Still, rip Twitter.com

Tried this, addon does not work at all even doing it :C

**Comment by rachasakr** [comment] 2024-05-17 06:37
> Some workaround(?): disable the add-on, open Twitter, site will redirect you to X with no loop, redirect successful, re-enable add-on, add-on works again.
> 
> Still, rip Twitter.com

+1 I tried this and it works. But now we stuck into disgusting X thing. 🥲

**Comment by VaelophisNyx** [comment] 2024-05-17 06:38
Also appears it's been pulled from the firefox extension store so
cool

**Comment by VaelophisNyx** [comment] 2024-05-17 06:46
Yeah there's a closed issue where its mentioned; apparently you're now forced to use a nightly/dev build of firefox if you want to continue to use this at all. I fucking hate modern browsers and websites.

**Comment by Aridow** [comment] 2024-05-17 07:44
I tried to install the last version that fixes it manually but Firefox says it has to be signed.

**Comment by VaelophisNyx** [comment] 2024-05-17 07:59
Yes that's why you have use a development build or nightly build (or go find the Unbranded version)
those don't require it. They also don't keep your login tokens and have technically partially separate profile storage so you get to re-do all your bookmarks and such

**Comment by themattreinhart** [comment] 2024-05-17 08:02
> I tried to install the last version that fixes it manually but Firefox says it has to be verified.

Same too. Idk if dimden has been notified yet but The Verge has confirmed on this thing that Twitter links has become X. Not working also in mine but it worked this morning (local time). 

Link: https://www.theverge.com/2024/5/17/23829098/twitter-x-com-url-links-switch

**Comment by ggtylerr** [comment] 2024-05-17 08:15
> Also appears it's been pulled from the firefox extension store so cool

Yeah, it seems OP's issue is 100% fixed in the latest version. The only problem is that its pulled from the FF store for whatever reason. So for any newcomers, you have two options:

* Use Chromium (i.e. Ungoogled, Brave, etc.)
* Use FF Nightly/Developer and disable `xpinstall.signatures.required` in `about:config`, restart, and [install the latest release from the zip file.](https://github.com/dimdenGD/OldTwitter/releases/latest)

**Comment by themattreinhart** [comment] 2024-05-17 08:19
> > Also appears it's been pulled from the firefox extension store so cool
> 
> Yeah, it seems OP's issue is 100% fixed in the latest version. The only problem is that its pulled from the FF store for whatever reason. So for any newcomers, you have two options:
> 
>     * Use Chromium (i.e. Ungoogled, Brave, etc.)
> 
>     * Use FF Nightly/Developer and disable `xpinstall.signatures.required` in `about:config`, restart, and [install the latest release from the zip file.](https://github.com/dimdenGD/OldTwitter/releases/latest)

The Chrome is to avail... seems idk with Mozilla pulled out the extension. Licensing reasons or someone (or X) took it down?

**Comment by ggtylerr** [comment] 2024-05-17 08:25
> > > Also appears it's been pulled from the firefox extension store so cool
> > 
> > 
> > Yeah, it seems OP's issue is 100% fixed in the latest version. The only problem is that its pulled from the FF store for whatever reason. So for any newcomers, you have two options:
> > ```
> > * Use Chromium (i.e. Ungoogled, Brave, etc.)
> > 
> > * Use FF Nightly/Developer and disable `xpinstall.signatures.required` in `about:config`, restart, and [install the latest release from the zip file.](https://github.com/dimdenGD/OldTwitter/releases/latest)
> > ```
> 
> The Chrome is to avail... seems idk with Mozilla pulled out the extension. Licensing reasons or someone (or X) took it down?

Sorry, I deleted the comment once I realized the latest version also doesn't work. Anyways, I don't see why someone would take down the FF page and not the Chrome page, so my guess is that one of the latest commits was seen as malicious (by Mozilla staff or whatever) and it got taken down. Without confirmation though, we can't do anything but speculate.

**Comment by themattreinhart** [comment] 2024-05-17 08:27
> > > > Also appears it's been pulled from the firefox extension store so cool
> > > 
> > > 
> > > Yeah, it seems OP's issue is 100% fixed in the latest version. The only problem is that its pulled from the FF store for whatever reason. So for any newcomers, you have two options:
> > > ```
> > > * Use Chromium (i.e. Ungoogled, Brave, etc.)
> > > 
> > > * Use FF Nightly/Developer and disable `xpinstall.signatures.required` in `about:config`, restart, and [install the latest release from the zip file.](https://github.com/dimdenGD/OldTwitter/releases/latest)
> > > ```
> > 
> > 
> > The Chrome is to avail... seems idk with Mozilla pulled out the extension. Licensing reasons or someone (or X) took it down?
> 
> Sorry, I deleted the comment once I realized the latest version also doesn't work. Anyways, I don't see why someone would take down the FF page and not the Chrome page, so my guess is that one of the latest commits was seen as malicious (by Mozilla staff or whatever) and it got taken down. Without confirmation though, we can't do anything but speculate.

Ok I can confirm in my end that it doesn't work also in Dev/Nightly or unbranded so it needs attention from the devs to change. Like what I said earlier when I posted the link from The Verge its already permanently changed... so I think it may take time to make changes before hand.

**Comment by Lorgra93** [comment] 2024-05-17 08:34
> > > > Also appears it's been pulled from the firefox extension store so cool
> > > 
> > > 
> > > Yeah, it seems OP's issue is 100% fixed in the latest version. The only problem is that its pulled from the FF store for whatever reason. So for any newcomers, you have two options:
> > > ```
> > > * Use Chromium (i.e. Ungoogled, Brave, etc.)
> > > 
> > > * Use FF Nightly/Developer and disable `xpinstall.signatures.required` in `about:config`, restart, and [install the latest release from the zip file.](https://github.com/dimdenGD/OldTwitter/releases/latest)
> > > ```
> > 
> > 
> > The Chrome is to avail... seems idk with Mozilla pulled out the extension. Licensing reasons or someone (or X) took it down?
> 
> Sorry, I deleted the comment once I realized the latest version also doesn't work. Anyways, I don't see why someone would take down the FF page and not the Chrome page, so my guess is that one of the latest commits was seen as malicious (by Mozilla staff or whatever) and it got taken down. Without confirmation though, we can't do anything but speculate.

It works, you just need to login one time without the extension enabled, to let the system "migrate" you.  
After that, the newer version of the addon works on my end.

**Comment by themattreinhart** [comment] 2024-05-17 08:38
> > > > > Also appears it's been pulled from the firefox extension store so cool
> > > > 
> > > > 
> > > > Yeah, it seems OP's issue is 100% fixed in the latest version. The only problem is that its pulled from the FF store for whatever reason. So for any newcomers, you have two options:
> > > > ```
> > > > * Use Chromium (i.e. Ungoogled, Brave, etc.)
> > > > 
> > > > * Use FF Nightly/Developer and disable `xpinstall.signatures.required` in `about:config`, restart, and [install the latest release from the zip file.](https://github.com/dimdenGD/OldTwitter/releases/latest)
> > > > ```
> > > 
> > > 
> > > The Chrome is to avail... seems idk with Mozilla pulled out the extension. Licensing reasons or someone (or X) took it down?
> > 
> > 
> > Sorry, I deleted the comment once I realized the latest version also doesn't work. Anyways, I don't see why someone would take down the FF page and not the Chrome page, so my guess is that one of the latest commits was seen as malicious (by Mozilla staff or whatever) and it got taken down. Without confirmation though, we can't do anything but speculate.
> 
> It works, you just need to login one time without the extension enabled, to let the system "migrate" you. After that, the newer version of the addon works on my end.

Ok it works with the new version. <3

**Comment by ggtylerr** [comment] 2024-05-17 08:43
@Lorgra93  I see. So current workaround is:
1. Go on Chromium or Firefox Dev/Nightly
2. Go on `twitter.com` and let it migrate over to `x.com`
    - You must have the extension disabled or uninstalled before this.
3. Download the new version
    - On Firefox, you have to disable `xpinstall.signatures.required` in `about:config`, restart your browser, and [download from the latest release.](https://github.com/dimdenGD/OldTwitter/releases/latest) You can load the zip file from `about:addons` -> Gear icon -> Install Add-On From File...

**Comment by themattreinhart** [comment] 2024-05-17 08:45
> @Lorgra93 I see. So current workaround is:
> 
>     1. Go on Chromium or Firefox Dev/Nightly
> 
>     2. Go on `twitter.com` and let it migrate over to `x.com`
>        
>        * You must have the extension disabled or uninstalled before this.
> 
>     3. Download the new version
>        
>        * On Firefox, you have to disable `xpinstall.signatures.required` in `about:config`, restart your browser, and [download from the latest release.](https://github.com/dimdenGD/OldTwitter/releases/latest) You can load the zip file from `about:addons` -> Gear icon -> Install Add-On From File...

Update on Chrome... the new version is only on FF Nightly/Dev but you'll need to disable the old one because it could create a conflict with the old vs new

**Comment by aLyinxz** [comment] 2024-05-17 09:41
ggtylerr's solution worked even on non-dev Firefox 115.11.0x64, but now pics don't go straight to original size
It opens like this: 
`pbs.twimg.com/media/GNsxOLCa4AAJxTQ.jpg`
Instead of this:
`pbs.twimg.com/media/GNsxOLCa4AAJxTQ?format=jpg&name=orig`

**Comment by themattreinhart** [comment] 2024-05-17 09:43
> ggtylerr's solution worked even on non-dev Firefox 115.11.0x64, but now pics don't go straight to original size It opens like this: `pbs.twimg.com/media/GNsxOLCa4AAJxTQ.jpg` Instead of this: `pbs.twimg.com/media/GNsxOLCa4AAJxTQ?format=jpg&name=orig`

Could be a formatting/code issue due to the link change?

**Comment by jacekszymanski** [comment] 2024-05-17 09:49
Also, after the move, with Strict protection enabled, twitter with the addon looks like this:

![image](https://github.com/dimdenGD/OldTwitter/assets/208228/23e2e11d-89ba-4f88-b4f5-a7dfd55398b8)

other elements are fscked up as well. Though I don't know if the addon can do anything about it; without the addon however the page doesn't work at all.

**Comment by themattreinhart** [comment] 2024-05-17 09:52
> Also, after the move, with Strict protection enabled, twitter with the addon looks like this:
> 
> ![image](https://private-user-images.githubusercontent.com/208228/331545296-23e2e11d-89ba-4f88-b4f5-a7dfd55398b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mzk3MzUsIm5iZiI6MTcxNTkzOTQzNSwicGF0aCI6Ii8yMDgyMjgvMzMxNTQ1Mjk2LTIzZTJlMTFkLTg5YmEtNGY4OC1iNGY1LWE3ZGZkNTUzOThiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwOTUwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTNlZmQ5NTJmYzcxN2VlM2ZiMzhmNmRmMWYxNDEyZDU5ZjE0OGE5YzIxMDE3NDM5Nzk5NjQ1NjBjZmUyYzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qhk-uhYJJl4H7K5Dg1KuP-LPMP_HZjukoFDy-7VCLAY)
> 
> other elements are fscked up as well. Though I don't know if the addon can do anything about it; without the addon however the page doesn't work at all.

Will it work with hard refresh (meaning using the server than cache) which is Shift+F5?

**Comment by jacekszymanski** [comment] 2024-05-17 10:03
> Will it work with hard refresh (meaning using the server than cache) which is Ctrl+Shift+R?

Well, it didn't, but it seems that Elon backed down on [this change](https://cybernews.com/news/x-twitter-not-working-on-firefox/), now both the page without the addon and the addon work as they should. 🤭

**Comment by ravstar52** [comment] 2024-05-17 10:12
Fix for OldTwitter not working (chrome instructions):
> - Three dots in the top right corner -> Extensions -> Manage Extensions
> - Turn OldTwitter on -> Accept the new permission requriements/changes
> - Turn OldTwitter off
> - In a new tab, open www.twitter.com
> - Let it redirect you to x.com
> - in a new tab, go to this site: `chrome://settings/cookies?search=Sites%20allowed%20to%20use%20third-party%20cookies`
> - Click `(Add)`
> - Enter the following: `[*.]x.com` -> Press `(Add)`
> - Click `(Add)` again.
> - Enter the following: `[*.]twitter.com` -> Press `(Add)`
> - Go back to the Extensions tab -> Turn on OldTwitter
> - reload your twitter tab

**Comment by aryoadhi** [comment] 2024-05-17 10:38
> @Lorgra93 I see. So current workaround is:
> 
> 1. Go on Chromium or Firefox Dev/Nightly
> 2. Go on `twitter.com` and let it migrate over to `x.com`
>    
>    * You must have the extension disabled or uninstalled before this.
> 3. Download the new version
>    
>    * On Firefox, you have to disable `xpinstall.signatures.required` in `about:config`, restart your browser, and [download from the latest release.](https://github.com/dimdenGD/OldTwitter/releases/latest) You can load the zip file from `about:addons` -> Gear icon -> Install Add-On From File...

This does not work in Firefox Stable 125.0.3 (64-bit) on Fedora Linux 40. A dev version might be needed for this to work.

**Comment by dimdenGD** [comment] 2024-05-17 12:16
It's not possible to make extension to continue having twitter.com link. As for migration, as mentioned early, on /x/migrate page you need to turn off extension, let it migrate you, and then you can enable extension again and it should work fine.
Firefox version of extension was removed from addons store, so to install extension permamently you need to get Firefox for Developers, disable `xpinstall.signatures.required` in `about:config`, install zip from Releases page in `about:addons`.

**Closed by dimdenGD** 2024-05-17 12:16 UTC
Labels: enhancement

**Comment by Aridow** [comment] 2024-05-17 17:46
> It's not possible to make extension to continue having twitter.com link. As for migration, as mentioned early, on /x/migrate page you need to turn off extension, let it migrate you, and then you can enable extension again and it should work fine. Firefox version of extension was removed from addons store, so to install extension permamently you need to get Firefox for Developers, disable `xpinstall.signatures.required` in `about:config`, install zip from Releases page in `about:addons`.

Will the add-on be back on the store in the future?

**Comment by dimdenGD** [comment] 2024-05-17 18:32
I submitted it for review again, so if it passes review it might be back in next week or so

**Comment by ggtylerr** [comment] 2024-05-17 23:28
> > @Lorgra93 I see. So current workaround is:
> > 
> > 1. Go on Chromium or Firefox Dev/Nightly
> > 2. Go on `twitter.com` and let it migrate over to `x.com`
> >    
> >    * You must have the extension disabled or uninstalled before this.
> > 3. Download the new version
> >    
> >    * On Firefox, you have to disable `xpinstall.signatures.required` in `about:config`, restart your browser, and [download from the latest release.](https://github.com/dimdenGD/OldTwitter/releases/latest) You can load the zip file from `about:addons` -> Gear icon -> Install Add-On From File...
> 
> This does not work in Firefox Stable 125.0.3 (64-bit) on Fedora Linux 40. A dev version might be needed for this to work.

Like I said, you need to have Dev or Nightly. Stable does not let you use unsigned extensions.

**Comment by Aridow** [comment] 2024-06-15 14:41
Seems like it's has been deleted from Firefox store once again.
