### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 6306** [dimdenGD/OldTwitter#41] opened 2023-01-16 03:33 UTC
TypeError: Cannot read properties of undefined (reading ’split’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1119:435) at async renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/home/script.js:337:17) at 1614387271310151680 (OldTwitter v1.6.6.0)

**Comment by dimdenGD** [comment] 2023-01-16 12:32
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/37

**Closed** 2023-01-16 12:33 UTC
Labels: bug
