### ISSUE TITLE
Changing colours only works for our profiles, is there a way to make it website wide?

### ISSUE THREAD

**Issue by xinomp** [dimdenGD/OldTwitter#191] opened 2023-07-08 10:32 UTC
Unless this is a bug, could this be an option in the future?

**Comment by dimdenGD** [comment] 2023-07-08 10:32
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/aeb2aa33-b44f-4bba-91c2-1bc9d507c8e9)

**Comment by xinomp** [comment] 2023-07-08 10:39
It doesn't work for me

**Comment by dimdenGD** [comment] 2023-07-08 14:41
Works fine for me

**Comment by homosexuayla** [comment] 2023-07-08 16:42
also doesn't work for me

the only way i could fix it is putting the color as a custom css var
like --link-color: rgb(255 120 180)

**Comment by xinomp** [comment] 2023-07-08 17:15
This actually worked for me

**Comment by TorutheRedFox** [comment] 2023-07-08 18:17
possible duplicate of my issue? (#96)

**Comment by dimdenGD** [comment] 2023-07-10 00:19
If someone has Discord, you can help me to debug this issue, my username on discord is `dimden`

**Closed** 2023-07-10 12:14 UTC
Labels: question
