### ISSUE TITLE
Pinned tweet won't show

### ISSUE THREAD

**Issue by MidwareLabs** [dimdenGD/OldTwitter#40] opened 2023-01-14 16:03 UTC
**Describe the bug**
Whenever I look at a user's page, it doesn't display the pinned tweet, and instead shows an error code

**To Reproduce**
Go on twitter, and open a user's page with a pinned tweet.

**Expected behavior**
No error code + shows the pinned tweet

**Screenshots**
![image](https://user-images.githubusercontent.com/118021201/212481446-b0052317-c82c-4186-a3ac-f9ceb21daba5.png)

**Browser**
Vivaldi 5.6.2867.58 (Stable channel) (64-bit) 
(Chromium browser)

**Code**
TypeError: Cannot read properties of undefined (reading ’split’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1119:435) at async renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:930:57) at 1601275834454646786 (OldTwitter v1.6.6.0)

**Comment by dimdenGD** [comment] 2023-01-14 16:04
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/37

**Closed by dimdenGD** 2023-01-14 16:04 UTC
Labels: bug
